"""
Gateway routes for serving reports and logs.

Security:
  - All routes require auth (except health)
  - Directory traversal blocked via Path.resolve() + startswith()
  - CSP + Cache-Control headers on all responses
  - Log files limited to .jsonl/.json/.txt/.log extensions
"""

from __future__ import annotations

import html as _html
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import FileResponse, HTMLResponse

from core.config import cfg
from core.gateway_backend.dependencies import check_auth
import json

router = APIRouter()

_LOG_EXTENSIONS = {".jsonl", ".json", ".txt", ".log"}

_CSP = (
    "default-src 'self'; "
    "script-src 'unsafe-inline' https://cdn.jsdelivr.net https://cdn.tailwindcss.com; "
    "style-src 'unsafe-inline' https://cdn.tailwindcss.com; "
    "img-src 'self' data:; "
    "frame-ancestors 'none'; "
    "connect-src 'none';"
)


def _reports_dir() -> Path:
    return cfg.workspace_root / "reports"


def _logs_dir() -> Path:
    """Explicit path: D:\mcp\agent\logs\agent"""
    return Path(cfg.agent_root) / "logs" / "agent"

def _list_reports() -> list[dict]:
    """Scan reports directory and return metadata for all reports."""
    reports = _reports_dir()
    if not reports.exists():
        return []

    result = []
    for trace_dir in sorted(reports.iterdir()):
        if not trace_dir.is_dir():
            continue
        manifest_path = trace_dir / "manifest.json"
        metrics_path = trace_dir / "metrics.json"
        entry = {
            "trace_id": trace_dir.name,
            "url": f"/reports/{trace_dir.name}/",
        }
        if manifest_path.exists():
            try:
                import json
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                entry.update({
                    "title": manifest.get("title", ""),
                    "action": manifest.get("action", ""),
                    "preset": manifest.get("preset", ""),
                    "created_at": manifest.get("created_at", ""),
                    "files": manifest.get("files", []),
                })
            except Exception:
                pass
        if metrics_path.exists():
            try:
                metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
                entry["metrics"] = metrics
            except Exception:
                pass
        result.append(entry)
    return result



def _dir_listing_html(path: Path, url_prefix: str, title: str) -> str:
    items = []
    for item in sorted(path.iterdir()):
        name = item.name
        if item.is_dir():
            name += "/"
        escaped_name = _html.escape(name)
        items.append(f'<li><a href="{url_prefix}{escaped_name}">{escaped_name}</a></li>')

    escaped_title = _html.escape(title)
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{escaped_title}</title>
<style>
body {{ font-family: ui-sans-serif, system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; background: #0f172a; color: #e2e8f0; }}
h1 {{ color: #0d9488; font-size: 1.5rem; border-bottom: 1px solid #334155; padding-bottom: 10px; }}
ul {{ list-style: none; padding: 0; }}
li {{ padding: 8px 0; border-bottom: 1px solid #1e293b; }}
a {{ color: #38bdf8; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.meta {{ color: #64748b; font-size: 0.85rem; margin-top: 20px; }}
</style>
</head>
<body>
<h1>{escaped_title}</h1>
<ul>
{chr(10).join(items) if items else '<li><em>Empty</em></li>'}
</ul>
<p class="meta">Generated by MCP Agent Gateway</p>
</body>
</html>"""


@router.get("/api/reports")
def list_reports(_: None = Depends(check_auth)):
    """List all reports with metadata."""
    reports = _list_reports()
    return {"reports": reports, "count": len(reports)}


@router.get("/reports/{trace_id}", response_class=HTMLResponse)
def report_dir(trace_id: str, _: None = Depends(check_auth)):
    """Directory listing for a specific trace_id."""
    safe_tid = "".join(c if c.isalnum() or c in "-_" else "_" for c in trace_id)
    trace_dir = _reports_dir() / safe_tid
    if not trace_dir.exists() or not trace_dir.is_dir():
        raise HTTPException(status_code=404, detail="Report not found")

    html = _dir_listing_html(trace_dir, f"/reports/{safe_tid}/", f"Report: {safe_tid}")
    return Response(
        content=html,
        media_type="text/html; charset=utf-8",
        headers={
            "Cache-Control": "no-store, private",
            "Content-Security-Policy": _CSP,
        },
    )


@router.get("/reports/{trace_id}/{filename}")
def report_file(trace_id: str, filename: str, _: None = Depends(check_auth)):
    """Serve a specific file from a trace_id directory."""
    safe_tid = "".join(c if c.isalnum() or c in "-_" else "_" for c in trace_id)
    trace_dir = _reports_dir() / safe_tid
    if not trace_dir.exists() or not trace_dir.is_dir():
        raise HTTPException(status_code=404, detail="Report not found")

    file_path = trace_dir / filename
    file_resolved = file_path.resolve()
    trace_resolved = trace_dir.resolve()
    if not str(file_resolved).startswith(str(trace_resolved)):
        raise HTTPException(status_code=403, detail="Forbidden")

    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="File not found")

    media_type = _guess_media_type(file_path)
    headers = {
        "Cache-Control": "no-store, private",
    }
    if media_type == "text/html; charset=utf-8":
        headers["Content-Security-Policy"] = _CSP

    return FileResponse(
        path=file_path,
        media_type=media_type,
        headers=headers,
    )


def _guess_media_type(file_path: Path) -> str:
    suffix = file_path.suffix.lower()
    return {
        ".html": "text/html; charset=utf-8",
        ".json": "application/json; charset=utf-8",
        ".jsonl": "application/jsonlines; charset=utf-8",
        ".txt": "text/plain; charset=utf-8",
        ".css": "text/css; charset=utf-8",
        ".js": "application/javascript; charset=utf-8",
        ".svg": "image/svg+xml",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
    }.get(suffix, "application/octet-stream")


@router.get("/logs/", response_class=HTMLResponse)
def log_dir(_: None = Depends(check_auth)):
    """List available log files."""
    logs = _logs_dir()
    if not logs.exists():
        return Response(
            content=_dir_listing_html(Path("."), "/logs/", "Logs (directory not found)"),
            media_type="text/html; charset=utf-8",
            headers={"Cache-Control": "no-store, private", "Content-Security-Policy": _CSP},
        )
    return Response(
        content=_dir_listing_html(logs, "/logs/", "Agent Logs"),
        media_type="text/html; charset=utf-8",
        headers={"Cache-Control": "no-store, private", "Content-Security-Policy": _CSP},
    )


@router.get("/logs/{filename}")
def log_file(filename: str, _: None = Depends(check_auth)):
    """Serve a specific log file."""
    file_path = _logs_dir() / filename
    file_resolved = file_path.resolve()
    logs_resolved = _logs_dir().resolve()
    if not str(file_resolved).startswith(str(logs_resolved)):
        raise HTTPException(status_code=403, detail="Forbidden")

    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="File not found")

    if file_path.suffix.lower() not in _LOG_EXTENSIONS:
        raise HTTPException(status_code=400, detail="Invalid file type")

    return FileResponse(
        path=file_path,
        media_type="text/plain; charset=utf-8",
        headers={"Cache-Control": "no-store, private"},
    )
