"""skills/ddm/inflation/__init__.py -- Inflation skill manifest + router.

DDM Inflation dashboard. 1 mode: dashboard (4-tab).

  Tabs:
    1. IGP-M       (group: Indices)   - KPIs + history chart + monthly matrix
    2. IPCA        (group: Indices)   - same
    3. INPC        (group: Indices)   - same
    4. Comparativo (group: Analise)   - overlay chart (12m acumulado, last 24m)

Calls data_sources.ddm.inflation query_engine directly (read-only - no own DB).

[v1] Skill structure mirrors the bcb/macro pattern:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_value, format_pct
  - report.py           : build_kpi_card, build_chart_section, build_table_section,
                          build_text_section, build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create inflation's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v1] Sync guard wired via required_sources=["ddm"]. skills/_base._trigger_sync
sync_map has a "ddm" entry that calls sync_all(force=True) when ddm is stale.
"""

from __future__ import annotations

from skills.ddm.inflation._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm-inflation"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "inflation",
    "description": (
        "DDM Inflation dashboard - 4 tabs: IGP-M, IPCA, INPC, Comparativo. "
        "Each index tab shows KPIs (month_value, year_acumulado, "
        "acumulado_12m) + historical chart (last 60 months) + monthly "
        "matrix table. Comparativo tab overlays 12m acumulado for all 3 "
        "indices (last 24 months). Data source: data_sources/ddm/inflation/ "
        "(read-only queries against inflation.db)."
    ),
    "source":  "data_sources/ddm/inflation/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "inflation", MODES,
                   required_sources=REQUIRED_SOURCES)
