"""
Phase 4b verification — run from D:/mcp/agent/
"""
import sys
print("=== Phase 4b: Visualize + File Extensions Verification ===\n")

# ── 1. file write_pdf ─────────────────────────────────────────────────────────
print("1. file(write_pdf)")
from tools.file_ops import file

content_md = """# Quarterly Report
## Executive Summary
Strong performance across all segments this quarter.

## Key Metrics
Revenue grew 18% year-over-year driven by new product launches.

### Regional Breakdown
Performance was strongest in the Southeast region.

---
Generated by MCP Agent
"""

r = file(action="write_pdf", path="autocode/test_report.pdf",
         content=content_md, title="Q3 Report")
assert r["status"] == "success", f"FAIL: {r}"
print(f"   write_pdf → {r['pages']} page(s), {r['size']} bytes ✓")

# ── 2. file write_docx ────────────────────────────────────────────────────────
print("\n2. file(write_docx)")
r = file(action="write_docx", path="autocode/test_report.docx",
         content=content_md, title="Q3 Report")
assert r["status"] == "success", f"FAIL: {r}"
print(f"   write_docx → {r['paragraphs']} paragraphs, {r['size']} bytes ✓")

# ── 3. visualize chart ────────────────────────────────────────────────────────
print("\n3. visualize(chart)")
from tools.visualize import visualize

r = visualize(
    type="chart", chart_type="bar",
    data={"x": ["Jan", "Feb", "Mar", "Apr"], "y": [120, 145, 132, 178]},
    title="Monthly Sales", x_label="Month", y_label="Revenue (R$)",
    output="test_bar_chart",
)
assert r["status"] == "success", f"FAIL: {r}"
print(f"   bar chart  → {r['html_path'].split(chr(92))[-1]} ✓")

r = visualize(
    type="chart", chart_type="line",
    data={"x": ["Jan", "Feb", "Mar", "Apr"], "y": [100, 118, 115, 139]},
    title="Revenue Trend", output="test_line_chart",
)
assert r["status"] == "success", f"FAIL: {r}"
print(f"   line chart → {r['html_path'].split(chr(92))[-1]} ✓")

r = visualize(
    type="chart", chart_type="pie",
    data={"names": ["SP", "RJ", "MG", "Other"], "values": [45, 25, 18, 12]},
    title="Revenue by State", output="test_pie_chart",
)
assert r["status"] == "success", f"FAIL: {r}"
print(f"   pie chart  → {r['html_path'].split(chr(92))[-1]} ✓")

# ── 4. visualize map ──────────────────────────────────────────────────────────
print("\n4. visualize(map)")
r = visualize(
    type="map", map_type="markers",
    data={
        "lat":    [-23.55, -22.91, -19.92, -30.03],
        "lon":    [-46.63, -43.17, -43.94, -51.23],
        "labels": ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Porto Alegre"],
        "colors": ["blue", "red", "green", "purple"],
    },
    title="Brazilian Cities", center_lat=-15.78, center_lon=-47.93, zoom=4,
    output="test_map_cities",
)
assert r["status"] == "success", f"FAIL: {r}"
print(f"   markers map → {r['html_path'].split(chr(92))[-1]} ✓")

# ── 5. visualize report ───────────────────────────────────────────────────────
print("\n5. visualize(report)")
r = visualize(
    type="report",
    title="Q3 Sales Report",
    subtitle="Brazilian Market Analysis",
    kpis=[
        {"label": "Total Revenue", "value": "R$1.2M"},
        {"label": "Growth",        "value": "+18%"},
        {"label": "New Clients",   "value": "847"},
        {"label": "Avg Ticket",    "value": "R$1,417"},
    ],
    sections=[
        {
            "title": "Executive Summary",
            "text":  "Strong Q3 driven by new product launches and expanded distribution.",
            "type":  "text",
        },
        {
            "title": "Sales by Month",
            "type":  "chart",
            "chart_data": {
                "chart_type": "bar",
                "x": ["July", "August", "September"],
                "y": [380000, 420000, 400000],
            },
        },
        {
            "title": "Top Performing Regions",
            "type":  "table",
            "data":  [
                {"Region": "Southeast",  "Revenue": "R$580K", "Growth": "+22%"},
                {"Region": "South",      "Revenue": "R$310K", "Growth": "+15%"},
                {"Region": "Northeast",  "Revenue": "R$210K", "Growth": "+11%"},
                {"Region": "Midwest",    "Revenue": "R$100K", "Growth": "+8%"},
            ],
        },
    ],
    output="test_report",
)
assert r["status"] == "success", f"FAIL: {r}"
print(f"   report → {r['html_path'].split(chr(92))[-1]} ({r['sections']} sections) ✓")

# ── 6. visualize dashboard ────────────────────────────────────────────────────
print("\n6. visualize(dashboard)")
r = visualize(
    type="dashboard",
    title="Sales Dashboard",
    subtitle="Real-time Performance Overview",
    columns=2,
    kpis=[
        {"label": "Revenue",     "value": "R$1.2M", "delta": "+18%"},
        {"label": "Orders",      "value": "2,847",  "delta": "+12%"},
        {"label": "Avg Ticket",  "value": "R$421",  "delta": "+5%"},
        {"label": "Churn Rate",  "value": "3.2%",   "delta": "-0.4%"},
    ],
    charts=[
        {
            "chart_type": "bar",
            "title":      "Revenue by Month",
            "data":       {"x": ["Jan","Feb","Mar","Apr"], "y": [100,145,132,178]},
            "color":      "#3498db",
        },
        {
            "chart_type": "pie",
            "title":      "Sales by Region",
            "data":       {"labels": ["SP","RJ","MG","Other"], "values": [45,25,18,12]},
        },
        {
            "chart_type": "line",
            "title":      "Customer Growth",
            "data":       {"x": ["Jan","Feb","Mar","Apr"], "y": [200,240,235,290]},
            "color":      "#27ae60",
        },
        {
            "chart_type": "area",
            "title":      "Daily Orders",
            "data":       {"x": ["Mon","Tue","Wed","Thu","Fri"], "y": [45,62,58,70,80]},
            "color":      "#e67e22",
        },
    ],
    output="test_dashboard",
)
assert r["status"] == "success", f"FAIL: {r}"
print(f"   dashboard → {r['html_path'].split(chr(92))[-1]} ({r['charts']} charts, {r['kpis']} KPIs) ✓")

# ── 7. Registry check ─────────────────────────────────────────────────────────
print("\n7. Registry check")
from mcp.server.fastmcp import FastMCP
from registry import register_all_tools

mcp   = FastMCP("test")
count = register_all_tools(mcp)
names = sorted([t.name for t in mcp._tool_manager.list_tools()])
print(f"   registered {count} tools: {names}")
assert "visualize" in names, "visualize not registered!"
assert count == 6, f"Expected 6 tools, got {count}"
print(f"   all 6 tools registered ✓")

print("\nPhase 4b complete.")
print("\nOpen these files in your browser to verify visuals:")
print(f"  D:\\mcp\\workspace\\visualizations\\")
print(f"  D:\\mcp\\workspace\\autocode\\test_report.pdf")
print(f"  D:\\mcp\\workspace\\autocode\\test_report.docx")
