"""skills/bcb/macro/__init__.py -- Macro skill manifest + router.

BCB macro-economic dashboard. 6 modes: dashboard (7-tab), rates, inflation,
fx, real_returns, expectations. Calls data_sources.bcb.sgs +
data_sources.bcb.focus query engines directly (read-only - no own DB).

[v3] Skill structure mirrors the CVM financials pattern:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback for bcb-sgs-v3 testing)
  - helpers.py          : format_value, compute_stats, build_observation_rows
  - report.py           : build_chart_section, build_table_section, build_kpi_card
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create macro's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v3] Sync guard wired via required_sources=["sgs"]. NOTE: skills/_base's
_trigger_sync sync_map does not yet know about the "sgs" source name (it
only maps CVM/B3 sources). The sync guard will record an error in
result["_sync"]["errors"] and proceed with whatever data is available -
users must run sync_all manually until the sync_map is extended (tracked
in ROADMAP P2).
"""

from __future__ import annotations

from skills.bcb.macro._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# [v3] Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
# [v1.4] focus added -- BCB Focus (Olinda OData) expectations survey.
# skills/_base._trigger_sync.sync_map now has a "focus" entry that calls
# sync_all(force=True) when focus is stale.
REQUIRED_SOURCES = ["sgs", "focus"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "macro",
    "description": (
        "BCB macro-economic dashboard. "
        "dashboard: 7-tab (Resumo/Juros/Inflacao/Cambio/Atividade/Retorno "
        "Real/Expectativas Focus). rates: Selic + CDI + TR + Meta Copom + "
        "Selic acumulada. inflation: IPCA + IGP-M (with rolling 12-month "
        "acumulado). fx: USD/BRL ptax diaria + mensal. real_returns: Fisher "
        "equation (Selic vs IPCA 12m). expectations: Focus survey (Olinda). "
        "Data sources: sgs (BCB SGS API) + focus (BCB Focus Olinda OData)."
    ),
    "source":  "data_sources/bcb/sgs/ + data_sources/bcb/focus/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# [v3] route() generated by make_route() with sync guard (when merged into
# the agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "macro", MODES,
                   required_sources=REQUIRED_SOURCES)
