"""skills/cvm/calculations/metrics/ -- Ratio metrics for historical analysis.

A METRIC composes ENGINES. Each metric is a standalone module that imports
the engines it needs and combines them into a ratio. Each metric produces
BOTH a per-share value AND a price ratio.

AUTO-DISCOVERY
--------------
Auto-discovery is handled by the TOP-LEVEL _registry.py
(skills/cvm/calculations/_registry.py), which globs both engines/*.py and
metrics/*.py. This file is a minimal docstring -- no auto-discovery code here,
NO manual inventory list. The registry is the source of truth.

To see the current metric inventory, use:
    from skills.cvm.calculations._registry import list_metrics, METRICS
    for name in list_metrics():
        spec = METRICS[name]
        print(f"{name}: {spec.per_share_label}+{spec.ratio_label} engines={spec.engines}")

Each metric module self-registers via `register_metric(MetricSpec(...))` at
module level. The registry holds all specs.

METRIC VS ENGINE -- READ THIS
-----------------------------
- ENGINES (in engines/): one per RAW QUANTITY. Each engine fetches ONE basic
  number at any historical date from its data source(s). Engines are leaves.
- METRICS (here): one per RATIO. A metric imports 2+ engines and combines them.
  Each metric produces BOTH a per-share value AND a price ratio.

To add a new METRIC:
  1. Confirm the engines you need already exist. If not, add the ENGINE first.
  2. Create metrics/<name>.py with:
     - <name>_at(company, date) -> per-share value
     - <ratio>_at(company, date) -> price ratio
     - <name>_history(company, date_from, date_to) -> list[dict]
  3. Call register_metric(MetricSpec(...)) at module level.
  4. That's it. The MANIFEST modes, ratio_history() dispatch, summary()
     metric-awareness, and chart adapter all auto-generate from the registry.
  5. Add tests in tests/skills/cvm/calculations/test_<name>.py.
  6. DO NOT edit this file -- the registry auto-discovers the new metric.
"""
