"""metrics/ocf_margin.py -- Operating Cash Flow Margin fundamental ratio metric.

OCF Margin = FCO / Revenue
           = Fluxo de Caixa Operacional / Receita Líquida

Measures how much operating cash flow a company generates per unit of
revenue. Unlike EBITDA Margin (which is an accrual-based operating profit
margin), OCF Margin reflects the actual cash generated by operations --
it accounts for working capital changes and is harder to manipulate via
accounting choices.

Fundamental ratio (no price, no shares). Composes operating_cf + revenue
engines.

Engines composed: operating_cf + revenue

Interpretation:
  - OCF Margin > 20%: excellent (high cash conversion)
  - OCF Margin 10-20%: good
  - OCF Margin < 5%: low (capital-intensive or low-margin business)
  - OCF Margin < 0%: company is burning cash from operations (red flag)
  - OCF Margin = None when revenue <= 0 (denominator guard)

Usage:
    from skills.cvm.calculations.metrics.ocf_margin import ocf_margin_at
    m = ocf_margin_at("PETR4", "2024-06-30")  # -> 0.18 (18%)
"""
from __future__ import annotations

from skills.cvm.calculations.engines.dfc.operating_cf import operating_cf_at, operating_cf_periods
from skills.cvm.calculations.engines.dre.revenue import revenue_at, revenue_periods
from skills.cvm.calculations._registry import MetricSpec, register_metric


def ocf_margin_at(company: str, date: str) -> float | None:
    """OCF Margin = FCO / Revenue.

    Args:
        company: Ticker, name, or CNPJ.
        date: YYYY-MM-DD.

    Returns:
        OCF Margin as a fraction (0.18 = 18%), or None if either component
        is missing or revenue <= 0 (denominator guard).
        FCO can be negative (cash burning from ops) -- the ratio is still
        meaningful and negative in that case.
    """
    fco = operating_cf_at(company, date)
    if fco is None:
        return None
    revenue = revenue_at(company, date)
    if revenue is None or revenue <= 0:
        return None
    return fco / revenue


def ocf_margin_history(company: str, date_from: str, date_to: str) -> list[dict]:
    """OCF Margin time series -- union of operating_cf + revenue period dates."""
    fco_periods_list = operating_cf_periods(company)
    rev_periods_list = revenue_periods(company)

    all_dates = set()
    for periods in [fco_periods_list, rev_periods_list]:
        for p in periods:
            if date_from <= p["date"] <= date_to:
                all_dates.add(p["date"])
    if not all_dates:
        return []

    result = []
    for date in sorted(all_dates):
        ttm_fco = None
        for fp in reversed(fco_periods_list):
            if fp["date"] <= date:
                ttm_fco = fp["ttm_fco"]
                break
        ttm_rev = None
        for rp in reversed(rev_periods_list):
            if rp["date"] <= date:
                ttm_rev = rp["ttm_rev"]
                break
        ocf_margin = None
        if (ttm_fco is not None
            and ttm_rev is not None and ttm_rev > 0):
            ocf_margin = ttm_fco / ttm_rev
        result.append({
            "date": date,
            "ocf_margin": ocf_margin,
            "ttm_fco": ttm_fco,
            "ttm_rev": ttm_rev,
        })
    return result


register_metric(MetricSpec(
    name="ocf_margin",
    per_share_label=None, per_share_key=None, per_share_fn=None,
    ratio_label="Margem FCO",
    ratio_key="ocf_margin",
    ratio_fn=ocf_margin_at,
    history_fn=ocf_margin_history,
    engines=["operating_cf", "revenue"],
    category="profitability",
    aliases=["margem_fco", "ocf_margem", "margem_operacional_caixa"],
))
