"""skills/ddm/poupanca/__init__.py -- Poupanca skill manifest + router.

DDM Poupanca dashboard. 1 mode: dashboard (1-tab with subtabs).

  Tab:
    1. Poupanca  (group: Renda Fixa)  - subtabs: Historico + Matriz
                                          (NO Comparativo tab - only 1 index)

The tab uses type:"subtabs" with 2 subtabs:
  - Historico subtab: 3-dataset chart (month_value + acumulado_no_ano +
                      acumulado_12m) + historico table (DESC, negative_red=True).
  - Matriz subtab:    heatmap (red->white->green diverging for all 12
                      month columns - NO "Ano" column since these are
                      monthly yields, not cumulative values).

Calls data_sources.ddm.poupanca query_engine directly (read-only - no own DB).

Skill structure mirrors the ddm/juros pattern:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_value, format_pct, _format_mes_ano, _heat_color
                          (returns dict, NOT string - v4 fix from juros)
  - report.py           : build_kpi_card, build_chart_section (3 datasets),
                          build_table_section (negative_red=True),
                          build_matrix_table_section (type="heatmap" with
                          {text, bg, color} cells), build_error_section.
                          NO build_overlay_chart_section (no Comparativo tab).
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create poupanca's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v1] Sync guard wired via required_sources=["ddm"]. skills/_base._trigger_sync
sync_map has a "ddm-poupanca" entry that calls sync_all(force=True) when the
"ddm-poupanca" source is stale.
"""

from __future__ import annotations

from skills.ddm.poupanca._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm-poupanca"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "poupanca",
    "description": (
        "DDM Poupanca dashboard - 1 tab: Poupanca. The tab uses subtabs "
        "(Historico + Matriz). Historico subtab shows KPIs (month_value, "
        "acumulado_no_ano, acumulado_12m) + a 3-dataset line chart "
        "(monthly yield %, year-to-date SUM %, rolling 12m SUM %) + "
        "history table (negative_red=True - poupanca yields can be negative "
        "during high-inflation periods). Matriz subtab shows a monthly "
        "matrix heatmap (red->white->green diverging for all 12 months - "
        "NO Ano column). NO Comparativo tab (only 1 index). Data source: "
        "data_sources/ddm/poupanca/ (read-only queries against poupanca.db)."
    ),
    "source":  "data_sources/ddm/poupanca/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "poupanca", MODES,
                   required_sources=REQUIRED_SOURCES)
