"""[v2.0] Create PR node — open a pull request from the autocode branch.

Split from node_publish (Phase 3.3). This node creates a PR after the branch
is pushed. Auto-merge is handled by node_merge_pr (next in graph).
"""
from __future__ import annotations

from core.config import cfg
from core.tracer import tracer
from workflows.autocode_impl.state import AutocodeState
from workflows.autocode_impl.github_ops import _github_pr_create


def _build_pr_body(state: AutocodeState) -> str:
    """Build a PR body from autocode state.

    # TODO(2.0): Richer PR body with test results, verification status,
    # swarm verdict, and diff summary. Currently minimal.
    """
    task = state.get("task", "")
    task_type = state.get("task_type", "")
    commit_sha = state.get("commit_sha", "")
    verification_passed = state.get("verification_passed", False)
    root_cause = state.get("root_cause", "")
    swarm_verdict = state.get("swarm_verdict", {})

    lines = [
        f"## Autocode: {task[:80]}",
        "",
        f"**Type:** {task_type}",
        f"**Commit:** {commit_sha or '(none)'}",
        f"**Verified:** {'yes' if verification_passed else 'no'}",
    ]

    if root_cause:
        lines.extend(["", f"**Root cause identified:** {root_cause[:200]}"])

    if swarm_verdict:
        confidence = swarm_verdict.get("confidence", "")
        agreement = swarm_verdict.get("agreement", "")
        providers = swarm_verdict.get("providers", 0)
        lines.extend([
            "",
            f"**Swarm review:** {confidence} confidence ({agreement}, {providers} providers)",
        ])
        if confidence == "LOW":
            lines.append(
                "⚠️ Low-confidence swarm verdict — please review the fix carefully."
            )

    lines.extend([
        "",
        "---",
        "*Generated by autocode v2.0*",
    ])
    return "\n".join(lines)


def node_create_pr(state: AutocodeState) -> dict:
    """[v2.0] Create PR from branch (if AUTOCODE_OPEN_PR=1 + branch pushed).

    Returns partial state update with:
      - pr_number: int (0 if not created)
      - pr_url: str ("" if not created)
    """
    tid = state.get("trace_id", "")

    # Skip conditions
    if state.get("status") in ("needs_clarification", "failed", "skipped"):
        return {}
    if not state.get("verification_passed"):
        return {}
    if state.get("dry_run"):
        return {}

    # If PR creation not enabled, skip
    if not cfg.autocode_open_pr:
        return {"pr_number": 0, "pr_url": ""}

    # Can't create a PR without pushing first
    if not state.get("pushed"):
        tracer.step(tid, "create_pr", "skipping PR — branch not pushed")
        return {"pr_number": 0, "pr_url": ""}

    branch = state.get("branch", "")
    if not branch:
        return {"pr_number": 0, "pr_url": ""}

    pr_title = f"autocode: {state.get('task', '')[:60]}"
    pr_body = _build_pr_body(state)
    pr_data = _github_pr_create(branch, pr_title, pr_body, tid)
    if pr_data:
        return {
            "pr_number": pr_data.get("number", 0),
            "pr_url": pr_data.get("url", ""),
        }
    return {"pr_number": 0, "pr_url": ""}
