"""[v1.3] Publish node for autocode workflow.

Runs after node_commit, before node_distill_memory. Handles the GitHub
publishing workflow:
  1. Push branch to remote (if AUTOCODE_PUSH_ON_COMMIT=1)
  2. Create PR (if AUTOCODE_OPEN_PR=1)
  3. Auto-merge PR (if AUTOCODE_AUTO_MERGE=1 — DANGEROUS, default off)

All operations graceful-skip if GitHub is not configured. This means
autocode works identically to v1.2 when no GitHub env vars are set.

# TODO(2.0): Consider splitting into separate push/pr/merge nodes for
# finer-grained routing and retry logic. Currently one node for simplicity.
"""
from __future__ import annotations

from core.config import cfg
from core.tracer import tracer
from workflows.autocode_impl.state import AutocodeState
from workflows.autocode_impl.github_ops import (
    _github_push,
    _github_pr_create,
    _github_pr_merge,
)


def _build_pr_body(state: AutocodeState) -> str:
    """Build a PR body from autocode state.

    # TODO(2.0): Richer PR body with test results, verification status,
    # swarm verdict, and diff summary. Currently minimal.
    """
    task = state.get("task", "")
    task_type = state.get("task_type", "")
    commit_sha = state.get("commit_sha", "")
    verification_passed = state.get("verification_passed", False)
    root_cause = state.get("root_cause", "")
    swarm_verdict = state.get("swarm_verdict", {})

    lines = [
        f"## Autocode: {task[:80]}",
        "",
        f"**Type:** {task_type}",
        f"**Commit:** {commit_sha or '(none)'}",
        f"**Verified:** {'yes' if verification_passed else 'no'}",
    ]

    if root_cause:
        lines.extend(["", f"**Root cause identified:** {root_cause[:200]}"])

    if swarm_verdict:
        confidence = swarm_verdict.get("confidence", "")
        agreement = swarm_verdict.get("agreement", "")
        providers = swarm_verdict.get("providers", 0)
        lines.extend([
            "",
            f"**Swarm review:** {confidence} confidence ({agreement}, {providers} providers)",
        ])
        if confidence == "LOW":
            lines.append(
                "⚠️ Low-confidence swarm verdict — please review the fix carefully."
            )

    lines.extend([
        "",
        "---",
        "*Generated by autocode v1.3*",
    ])
    return "\n".join(lines)


def node_publish(state: AutocodeState) -> dict:
    """[v1.3] Push branch + create PR + optional auto-merge.

    All operations gated on config flags + is_configured().
    Graceful skip if GitHub not configured or flags are off.
    """
    tid = state.get("trace_id", "")

    # Skip conditions — same as node_commit
    if state.get("status") in ("needs_clarification", "failed", "skipped"):
        return {}
    if not state.get("verification_passed"):
        return {}
    if state.get("dry_run"):
        tracer.step(tid, "publish", "dry_run=True — skipping push/PR")
        return {"status": "dry_run"}

    # If no publishing flags are set, skip entirely (v1.2 behavior)
    if not (cfg.autocode_push_on_commit or cfg.autocode_open_pr or cfg.autocode_auto_merge):
        return {}

    branch = state.get("branch", "")
    if not branch:
        tracer.step(tid, "publish", "no branch in state — skipping")
        return {}

    result: dict = {"pushed": False, "pr_number": 0, "pr_url": ""}

    # Step 1: Push (if enabled)
    if cfg.autocode_push_on_commit:
        success = _github_push(branch, tid)
        result["pushed"] = success
        if not success:
            # Push failed — don't proceed to PR creation
            # TODO(2.0): Add retry logic for transient push failures
            return result
    else:
        # Can't create a PR without pushing first
        if cfg.autocode_open_pr or cfg.autocode_auto_merge:
            tracer.step(tid, "publish", "skipping PR — AUTOCODE_PUSH_ON_COMMIT not enabled")
            return result

    # Step 2: Create PR (if enabled)
    if cfg.autocode_open_pr and result.get("pushed"):
        pr_title = f"autocode: {state.get('task', '')[:60]}"
        pr_body = _build_pr_body(state)
        pr_data = _github_pr_create(branch, pr_title, pr_body, tid)
        if pr_data:
            result["pr_number"] = pr_data.get("number", 0)
            result["pr_url"] = pr_data.get("url", "")
        else:
            # PR creation failed — don't proceed to auto-merge
            return result

    # Step 3: Auto-merge (if enabled — DANGEROUS, default off)
    # TODO(2.0): Add AUTOCODE_AUTO_MERGE_METHOD config (squash/merge/rebase)
    if cfg.autocode_auto_merge and result.get("pr_number"):
        _github_pr_merge(result["pr_number"], tid)

    return result
