"""skills/b3/options/__init__.py -- B3 options skill manifest + router.

B3 options (derivatives) analytics. The derivatives table
(`cotahist_derivatives`) lives in the SAME cotahist.db used by the price
skill. The IV tab also reads the Selic rate from `sgs.db` (BCB SGS series
432 = "Meta Selic Copom") as the risk-free rate for Black-Scholes pricing.
The Posições em Aberto tab (v1.3) reads open interest + position breakdown
from the B3 API CSV bulk download (`derivatives.db` + `instruments.db`).
So REQUIRED_SOURCES = ["cotahist", "sgs", "b3-api-derivatives",
"b3-api-instruments"] (the sync guard triggers all four sync engines if
any is stale).

Skill structure mirrors skills/b3/price + skills/bcb/macro:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
  - helpers.py          : format_value, format_brl, format_int, format_pct
  - engines.py          : [v1.2] Black-Scholes pricing + implied_vol
  - report.py           : build_chart_section, build_table_section,
                          build_kpi_card, build_text_section,
                          build_error_section, build_heatmap_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery:
  1. _registry.py calls make_registry() to create options' MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.
"""
from __future__ import annotations

from skills._base import auto_discover_modes, make_route, build_manifest_modes
from skills.b3.options._registry import MODES  # noqa: F401

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# [v1.2] The IV tab reads the Selic rate from sgs.db (BCB SGS series 432).
# [v1.3] The Posições em Aberto tab reads open interest from the B3 API
# CSV bulk download — derivatives.db (open positions + breakdown by
# holder/writer/covered/uncovered) joined with instruments.db (strike,
# expiration date, option style, company name) on TckrSymb. The Cadeia
# de Opções tab is also enriched with OI/Coberta/Descoberta columns from
# derivatives.db. So the sync guard must trigger FOUR sync engines if any
# is stale: cotahist (derivatives + spot prices), sgs (Selic rate),
# b3-api-derivatives (open positions), b3-api-instruments (option metadata).
REQUIRED_SOURCES = ["cotahist", "sgs", "b3-api-derivatives", "b3-api-instruments"]

MANIFEST = {
    "sub_domain":  "options",
    "description": (
        "B3 options (derivatives) analytics. "
        "dashboard: 6-tab (Cadeia de Opções + Put/Call Ratio + Volume por "
        "Strike + Exercicios + Volatilidade Implícita + Posições em Aberto). "
        "The IV tab uses Black-Scholes + the Selic rate from BCB SGS. The "
        "Posições em Aberto tab uses the B3 API CSV bulk download "
        "(derivatives.db + instruments.db) for open interest + position "
        "breakdown. Sources: cotahist.db (cotahist_derivatives + equities "
        "tables) + sgs.db (Selic rate, series 432) + b3/derivatives.db + "
        "b3/instruments.db (B3 API CSV bulk download)."
    ),
    "source":  "data_sources.b3.cotahist (shared cotahist.db) + data_sources.bcb.sgs (sgs.db) + data_sources.b3.api (derivatives.db + instruments.db)",
    "storage": "read-only — no own database",
    "modes": build_manifest_modes(MODES),
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree). Pass skip_sync=True per-call to bypass (e.g. for cached lookups).
route = make_route("sub_domain", "options", MODES,
                   required_sources=REQUIRED_SOURCES)
