"""skills/ddm/fluxo/__init__.py -- Fluxo skill manifest + router.

DDM Fluxo (B3 investment flow) dashboard. 1 mode: dashboard (multi-tab).

  Tabs:
    1. Fluxo         (group: Fluxo)        - KPIs + 4-dataset bar chart + sortable table
    2. Estrangeiro   (group: Investidores) - 3 subtabs (Diario/Mensal/Anual)
    3. Institucional (group: Investidores) - same
    4. Pessoa fisica (group: Investidores) - same
    5. Inst. Financeira (group: Investidores) - same

Calls data_sources.ddm.fluxo query_engine directly (read-only - no own DB).

[v1] Skill structure mirrors the ddm/focus pattern (1 dashboard mode):
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_brl, format_int, format_pct, format_date,
                          format_value
  - report.py           : build_kpi_card, build_fluxo_table, build_fluxo_chart,
                          build_investor_daily_chart, build_investor_monthly_chart,
                          build_investor_annual_chart, build_investor_table,
                          build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create fluxo's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v1] Sync guard wired via required_sources=["ddm-fluxo"]. skills/_base
._trigger_sync sync_map has a "ddm-fluxo" entry that calls
sync_all(force=True) when ddm-fluxo is stale.
"""

from __future__ import annotations

from skills.ddm.fluxo._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm-fluxo"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "fluxo",
    "description": (
        "DDM Fluxo (B3 investment flow) dashboard - 5 tabs: 1 'Fluxo' "
        "tab (group: Fluxo) with KPIs + 4-dataset daily bar chart + "
        "sortable table of all daily observations + 4 per-investor tabs "
        "(group: Investidores: Estrangeiro, Institucional, Pessoa fisica, "
        "Inst. Financeira) each with 3 subtabs (Diario/Mensal/Anual) "
        "showing a daily bar chart, a monthly cumulative line chart, "
        "and a running annual cumulative line chart. Data source: "
        "data_sources/ddm/fluxo/ (read-only queries against fluxo.db)."
    ),
    "source":  "data_sources/ddm/fluxo/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "fluxo", MODES,
                   required_sources=REQUIRED_SOURCES)
