"""skills/b3/term/__init__.py -- B3 term (a termo) skill manifest + router.

B3 term (a termo) contracts analytics. The derivatives table
(`cotahist_derivatives`) lives in the SAME cotahist.db used by the price +
options skills, so REQUIRED_SOURCES = ["cotahist"] (the sync guard reuses
the cotahist sync engine -- no separate sync for derivatives).

Term contracts (BDI 26/74) are bilateral agreements to buy/sell a stock at
a future date at a fixed price. The `close` field = the agreed future price
(term price), NOT the spot price. The ticker IS the share-class ticker
(PETR4 ≠ PETR3) -- it is NOT stripped.

Skill structure mirrors skills/b3/options:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
  - helpers.py          : format_value, format_brl, format_int
  - report.py           : build_chart_section, build_table_section,
                          build_text_section, build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery:
  1. _registry.py calls make_registry() to create term's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.
"""
from __future__ import annotations

from skills._base import auto_discover_modes, make_route, build_manifest_modes
from skills.b3.term._registry import MODES  # noqa: F401

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Same DB as cotahist (the cotahist_derivatives table lives in cotahist.db).
# The sync guard triggers cotahist sync if stale -- derivatives ride on the
# same DB so no separate source is declared.
REQUIRED_SOURCES = ["cotahist"]

MANIFEST = {
    "sub_domain":  "term",
    "description": (
        "B3 term (a termo) contracts dashboard. "
        "dashboard: 3-tab (Contratos Ativos + Spread Termo vs Spot + "
        "Volume Histórico). "
        "Source: cotahist.db (cotahist_derivatives table)."
    ),
    "source":  "data_sources.b3.cotahist.derivatives_query (shared cotahist.db)",
    "storage": "read-only — no own database",
    "modes": build_manifest_modes(MODES),
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree). Pass skip_sync=True per-call to bypass (e.g. for cached lookups).
route = make_route("sub_domain", "term", MODES,
                   required_sources=REQUIRED_SOURCES)
