"""skills/ddm/dividends/__init__.py -- Dividends skill manifest + router.

DDM Dividends dashboard. 1 mode: dashboard (1-tab).

  Tab:
    1. Dividendos  (group: Dividendos)  - KPIs + distribution chart + sortable table

Calls data_sources.ddm.dividends query_engine directly (read-only - no own DB).

Skill structure mirrors the ddm/inflation + ddm/juros + ddm/poupanca pattern:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_brl, format_int, format_pct, format_value,
                          format_date (YYYY-MM-DD -> DD/MM/YYYY PT-BR display)
  - report.py           : build_kpi_card, build_dividends_table (sortable=True),
                          build_distribution_chart (grouped bar: Dividendo vs
                          JCP per value range), build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create dividends's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

[v1] Sync guard wired via required_sources=["ddm-dividends"]. skills/_base.
_trigger_sync sync_map has a "ddm-dividends" entry that calls sync_all(
force=True) when the "ddm-dividends" source is stale.
"""

from __future__ import annotations

from skills.ddm.dividends._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm-dividends"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "dividends",
    "description": (
        "DDM Dividends dashboard - 1 tab: Dividendos. The tab shows 4 KPIs "
        "(total dividendos, valor total, maior dividendo, proximo "
        "pagamento) + a grouped bar distribution chart (Dividendo vs JCP "
        "per value range: <0.05, 0.05-0.10, 0.10-0.25, 0.25-0.50, "
        "0.50-1.00, 1.00-2.00, 2.00-5.00, >=5.00) + a sortable dividends "
        "table (default sort: Valor DESC). Column headers are clickable; "
        "clicking toggles asc/desc. Numeric cells carry data-value attrs "
        "for accurate sorting. Dates stored as YYYY-MM-DD in DB but "
        "displayed as DD/MM/YYYY (PT-BR). NO price colors on Valor column "
        "(dividend amounts, not stock prices). Data source: "
        "data_sources/ddm/dividends/ (read-only queries against dividends.db)."
    ),
    "source":  "data_sources/ddm/dividends/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "dividends", MODES,
                   required_sources=REQUIRED_SOURCES)
