"""skills/ddm/juros/__init__.py -- Juros skill manifest + router.

DDM Juros dashboard. 1 mode: dashboard (4-tab with subtabs).

  Tabs:
    1. Selic       (group: Indices)   - subtabs: Historico + Matriz
    2. Meta Selic  (group: Indices)   - same
    3. CDI         (group: Indices)   - same
    4. Comparativo (group: Analise)   - overlay chart (month_value, last 24m)

Each per-index tab uses type:"subtabs" with 2 subtabs:
  - Historico subtab: 3-dataset chart (month_value + media_no_ano +
                       media_12m) + historico table (DESC).
  - Matriz subtab:    heatmap (red->white->green diverging for all 12
                       month columns - NO "Ano" column since these are
                       daily rates, not acumulado).

Calls data_sources.ddm.juros query_engine directly (read-only - no own DB).

[v1] Skill structure mirrors the bcb/macro + ddm/inflation pattern:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_value, format_pct
  - report.py           : build_kpi_card, build_chart_section, build_table_section,
                          build_matrix_table_section, build_overlay_chart_section,
                          build_text_section, build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create juros's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v1] Sync guard wired via required_sources=["ddm"]. skills/_base._trigger_sync
sync_map has a "ddm-juros" entry that calls sync_all(force=True) when the
"ddm-juros" source is stale.
"""

from __future__ import annotations

from skills.ddm.juros._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "juros",
    "description": (
        "DDM Juros dashboard - 4 tabs: Selic, Meta Selic, CDI, Comparativo. "
        "Each index tab uses subtabs (Historico + Matriz). Historico "
        "subtab shows KPIs (month_value, media_no_ano, media_12m) + a "
        "3-dataset line chart (daily rate %, year-to-date average %, "
        "rolling 12m average %) + history table. Matriz subtab shows a "
        "monthly matrix heatmap (red->white->green diverging for all 12 "
        "months - NO Ano column). Comparativo tab overlays month_value "
        "for all 3 indices (last 24 months). Data source: "
        "data_sources/ddm/juros/ (read-only queries against juros.db)."
    ),
    "source":  "data_sources/ddm/juros/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "juros", MODES,
                   required_sources=REQUIRED_SOURCES)
