"""skills/ddm/acoes/__init__.py -- Acoes skill manifest + router.

DDM Acoes dashboard. 1 mode: dashboard (1-tab).

  Tab:
    1. Acoes (group: Acoes) - KPIs + sortable stocks table

Calls data_sources.ddm.acoes query_engine directly (read-only - no own DB).

[v1] Skill structure mirrors the ddm/inflation + ddm/juros + ddm/poupanca
patterns:
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_value, format_brl, format_int, format_pct
  - report.py           : build_kpi_card, build_table_section (sortable!),
                          build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create acoes's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v1] Sync guard wired via required_sources=["ddm-acoes"]. skills/_base
._trigger_sync sync_map has a "ddm-acoes" entry that calls
sync_all(force=True) when ddm-acoes is stale.
"""

from __future__ import annotations

from skills.ddm.acoes._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm-acoes"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "acoes",
    "description": (
        "DDM Acoes dashboard - 1 tab: Acoes. Shows KPIs (total stocks, "
        "most traded, biggest gainer, biggest loser) + a sortable stocks "
        "table (Ticker | Nome | Negocios | Ultima (R$) | Variacao). "
        "Click column headers to sort asc/desc. Default sort: Negocios DESC. "
        "Negative variation values render in red. Data source: "
        "data_sources/ddm/acoes/ (read-only queries against acoes.db)."
    ),
    "source":  "data_sources/ddm/acoes/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "acoes", MODES,
                   required_sources=REQUIRED_SOURCES)
