"""skills/cvm/valuation/__init__.py -- Valuation skill manifest + router.

Combines b3 price data + CVM DFP financials + FRE shares to compute
valuation ratios: P/L, P/VPA, EV, P/EBIT, P/FCO, Dividend Yield, Market Cap.

Data sources used:
  - data_sources/b3/api (trades.db — latest price)
  - data_sources/cvm/dfp (dfp.db — annual financials)
  - data_sources/cvm/fre (fre.db — shares outstanding)
  - data_sources/cvm/bridge (ticker → CNPJ → empresa_ids)

[v1.14] Sync guard wired via required_sources. The route() wrapper checks
freshness of all required sources before each dispatch and triggers force-sync
if any source is older than 24h (or missing). Tests use CVM_SKIP_SYNC=1.

Uses core/br_validator for parse_escala, validate_ticker.

Auto-discovery (via skills._base):
  1. _registry.py calls make_registry() to create valuation's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.
"""

from __future__ import annotations

from skills._base import auto_discover_modes, make_route, build_manifest_modes
from skills.cvm.valuation._registry import MODES  # noqa: F401

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# [v1.14] Data sources this skill needs. The route() wrapper checks
# freshness before each dispatch and triggers force-sync if any source
# is older than 24h (or missing). Tests use CVM_SKIP_SYNC=1 to bypass.
# cotahist is for daily price data.
REQUIRED_SOURCES = ["dfp", "itr", "fca", "cotahist", "brapi", "bridge"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "valuation",
    "description": (
        "Valuation ratios (P/L, P/VPA, EV, Dividend Yield, P/EBIT, P/FCO) "
        "combining b3 price + CVM financials + FRE shares. "
        "The investsite goldmine — computed from local data."
    ),
    "source":  "b3 trades.db + cvm dfp.db + cvm fre.db + bridge.db",
    "storage": "read-only — no own database",
    "modes": build_manifest_modes(MODES),
    # [v1.14] Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# [v1.14] route() now generated by make_route() with sync guard.
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "valuation", MODES,
                   required_sources=REQUIRED_SOURCES)
