"""tools/agent.py — Agent meta-tool (thin @tool facade).

Replaces the monolithic Phase 7 agent() with a true thin facade.
All business logic lives in agent_ops/ submodules:
  - actions/ — MCP-visible operations (dispatch, metrics, vision_delegate, clear_cache)
  - roles/ — Per-role prompts and configs (classify, route, research, etc.)
  - context.py — Context trimming and token estimation
  - cache.py — Response caching for deterministic roles
  - metrics.py — Per-role metrics collection
  - parse_warnings.py — JSON parse failure logging
  - json_extract.py — Brace-counting JSON extraction

The LLM sees ONE tool: agent(action, role, task, ...)
The facade validates inputs, looks up the action handler, and delegates.
"""
from __future__ import annotations

from registry import tool
from tools._meta_tool import meta_tool
from tools.agent_ops._registry import DISPATCH
from core.tracer import tracer
from core.utils import compress_result
from core.contracts import fail

# Ensure actions and roles are registered before @meta_tool runs
# This import triggers agent_ops/__init__.py auto-discovery
from tools.agent_ops import ROLES  # noqa: F401

PARALLEL_SAFE = False

@tool
@meta_tool(
    DISPATCH.get("agent", {}),
    doc_sections=[
        "IMPORTANT — action vs role:",
        ' action — what operation to perform: "dispatch" | "metrics" | "vision_delegate" | "clear_cache"',
        ' role — which LLM persona to use (only for action="dispatch"): classify | route | research | summarize | extract | critique | analyze | code | review | plan | consultor | refactor | test | document',
        "",
        "Common usage patterns:",
        ' agent(action="dispatch", role="classify", task="Is this spam?")',
        ' agent(action="dispatch", role="plan", task="Build a web scraper")',
        ' agent(action="metrics", task="classify") # query per-role metrics',
        ' agent(action="vision_delegate", task="Describe this image", context="image.png")',
        ' agent(action="clear_cache") # clear response cache',
        "",
        "For vision_delegate action:",
        ' context = file_path or public URL to the image',
        ' content = base64-encoded image string (optional)',
    ],
)
def agent(
    action: str = "",
    role: str = "",
    task: str = "",
    context: str = "",
    content: str = "",
    trace_id: str = "",
    temperature: float = -1.0,
    max_tokens: int = -1,
    mime_type: str = "",
    vision_json_mode: bool = False,
) -> dict:
    """
    Agent meta-tool — atomic actions for cognitive tasks.
    Docstring and action: Literal[...] are auto-generated by @meta_tool.
    """
    action = action.strip().lower()

    if not trace_id:
        trace_id = tracer.new_trace("agent", goal=action)

    # Fast path: empty action parameter
    if not action:
        return fail(
            "action parameter is required. Valid actions are listed in the tool description.",
            trace_id=trace_id,
        )

    # Cancellation Guard: Abort before any LLM or tool mutations
    try:
        from core.runtime.cancellation import ensure_not_cancelled
        ensure_not_cancelled(trace_id)
    except BaseException:
        return fail("Workflow cancelled — aborting agent operation", trace_id=trace_id)

    # Lookup action in registry
    agent_ops = DISPATCH.get("agent", {})
    op_info = agent_ops.get(action)
    if not op_info:
        valid = " | ".join(sorted(agent_ops.keys()))
        return fail(
            f"Unknown action '{action}'. Valid: {valid}",
            trace_id=trace_id,
        )

    # Build kwargs — pass through all relevant parameters
    kwargs = {
        "role": role,
        "task": task,
        "context": context,
        "content": content,
        "trace_id": trace_id,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "mime_type": mime_type,
        "vision_json_mode": vision_json_mode,
    }
    # Filter out None defaults so handlers only get what they need
    # Keep False, "", [] — those are explicit values, not "not provided"
    kwargs = {k: v for k, v in kwargs.items() if v is not None}

    # Execute handler safely
    try:
        result = op_info["func"](**kwargs)
        if isinstance(result, dict):
            if result.get("status") == "ok":
                result["status"] = "success"
            if trace_id and "trace_id" not in result:
                result["trace_id"] = trace_id
            return compress_result(result)
        return fail(
            f"Handler for '{action}' returned {type(result).__name__}, expected dict",
            trace_id=trace_id,
        )
    except Exception as e:
        return fail(str(e), trace_id=trace_id)
