"""
tools/file.py — File meta-tool.

The LLM sees ONE tool: file(action, ...)
All paths are resolved relative to agent_root (the project) unless absolute
or explicitly scoped to workspace. Paths outside workspace_root and agent_root
are rejected for safety.
"""
from __future__ import annotations

from registry import tool
from tools._meta_tool import meta_tool
from tools.file_ops._registry import DISPATCH
from core.path_guard import resolve_path, check_protected_file, make_path_error
from core.tracer import tracer
from core.utils import compress_result
from core.contracts import ok, fail

# ─────────────────────────────────────────────────────────────────────────────
# Dispatcher Implementation
# ─────────────────────────────────────────────────────────────────────────────
@tool
@meta_tool(
    DISPATCH.get("file", {}),
    doc_sections=[
        "IMPORTANT — path parameter:",
        ' path — file or directory path, relative to agent_root or workspace_root',
        ' Absolute paths are allowed if within allowed roots.',
        "",
        "Common usage patterns:",
        ' file(action="read_file", path="scripts/analysis.py")',
        ' file(action="write_file", path="output/report.md", content="# Report\n...")',
        ' file(action="list_directory", path=".")',
        ' file(action="read_multiple_files", paths=["a.py", "b.py"])',
        ' file(action="search_files", query="ChromaDB collection", max_results=5)',
        ' file(action="directory_tree", path=".", max_depth=3)',
        ' file(action="find_files", pattern="**/*.py", path=".")',
        ' file(action="append_file", path="logs/app.log", content="New line\n")',
        "",
        "Destructive actions require explicit flags:",
        ' delete_file — requires force=True',
        ' move_file — overwrites if force=True',
        ' copy_file — overwrites if force=True',
    ],
)
def file(
    action: str = "",
    path: str = "",
    paths: list[str] | None = None,
    content: str = "",
    query: str = "",
    pattern: str = "",
    max_chars: int | None = None,
    max_results: int | None = None,
    head: int | None = None,
    tail: int | None = None,
    max_depth: int | None = None,
    max_bytes: int | None = None,
    exclude_patterns: list[str] | None = None,
    old: str = "",
    new: str = "",
    edits: list[dict] | None = None,
    dry_run: bool = False,
    force: bool = False,
    recursive: bool = False,
    parents: bool = True,
    source: str = "",
    destination: str = "",
    trace_id: str = "",
) -> dict:
    """
    File tool — read, write, search, and manage files.
    Docstring and action: Literal[...] are auto-generated by @meta_tool.
    """
    action = action.strip().lower()
    if not trace_id:
        trace_id = tracer.new_trace("file", goal=action)

    # Fast path: empty action parameter
    if not action:
        return fail(
            "action parameter is required. Valid actions are listed in the tool description.",
            trace_id=trace_id,
        )

    # Cancellation Guard: Abort before any file mutations
    import asyncio
    try:
        from core.runtime.cancellation import ensure_not_cancelled
        ensure_not_cancelled(trace_id)
    except asyncio.CancelledError:
        return fail("Workflow cancelled — aborting file operation", trace_id=trace_id)

    # 1. Lookup action in registry
    file_ops = DISPATCH.get("file", {})
    op_info = file_ops.get(action)
    if not op_info:
        valid = " | ".join(sorted(file_ops.keys()))
        return fail(
            f"Unknown action '{action}'. Valid: {valid}",
            trace_id=trace_id,
        )

    # 2. Validate single path (if provided)
    resolved_path = None
    if path:
        resolved, err = resolve_path(path, default_root="agent")
        if not resolved:
            return make_path_error(path, action, err, trace_id)
        allowed, err = check_protected_file(resolved, action)
        if not allowed:
            return make_path_error(path, action, err, trace_id)
        resolved_path = str(resolved)

    # 3. Validate multiple paths (for read_multiple_files, etc.)
    # NOTE: For read_multiple_files, we validate paths but allow missing ones
    # The handler will report per-file errors instead of failing the whole batch.
    resolved_paths = None
    if paths:
        new_paths = []
        for p in paths:
            resolved, err = resolve_path(p, default_root="agent")
            if not resolved:
                if action == "read_multiple_files":
                    # Pass original path — handler will call _safe_resolve and report per-file error
                    new_paths.append(p)
                    continue
                return make_path_error(p, action, err, trace_id)
            allowed, err = check_protected_file(resolved, action)
            if not allowed:
                if action == "read_multiple_files":
                    # Pass original path — handler will call _safe_resolve and report per-file error
                    new_paths.append(p)
                    continue
                return make_path_error(p, action, err, trace_id)
            new_paths.append(str(resolved))
        resolved_paths = new_paths

    # 4. Validate source/destination (for move_file, copy_file)
    resolved_source = None
    resolved_destination = None
    if source:
        resolved, err = resolve_path(source, default_root="agent")
        if not resolved:
            return make_path_error(source, action, err, trace_id)
        allowed, err = check_protected_file(resolved, action)
        if not allowed:
            return make_path_error(source, action, err, trace_id)
        resolved_source = str(resolved)
    if destination:
        resolved, err = resolve_path(destination, default_root="agent")
        if not resolved:
            return make_path_error(destination, action, err, trace_id)
        # Note: destination may not exist yet (e.g., for write_file)
        # Only check protected if it exists
        if resolved.exists():
            allowed, err = check_protected_file(resolved, action)
            if not allowed:
                return make_path_error(destination, action, err, trace_id)
        resolved_destination = str(resolved)

    # 5. Build kwargs — only pass non-None values to handler
    kwargs = {
        "path": resolved_path,
        "paths": resolved_paths,
        "content": content,
        "query": query,
        "pattern": pattern,
        "max_chars": max_chars,
        "max_results": max_results,
        "head": head,
        "tail": tail,
        "max_depth": max_depth,
        "max_bytes": max_bytes,
        "exclude_patterns": exclude_patterns,
        "old": old,
        "new": new,
        "edits": edits,
        "dry_run": dry_run,
        "force": force,
        "recursive": recursive,
        "parents": parents,
        "source": resolved_source,
        "destination": resolved_destination,
        "trace_id": trace_id,
    }
    # Filter out None defaults so handlers only get what they need
    # Keep False, "", [] — those are explicit values, not "not provided"
    kwargs = {k: v for k, v in kwargs.items() if v is not None}

    # 6. Execute handler safely
    try:
        result = op_info["func"](**kwargs)
        if isinstance(result, dict):
            if result.get("status") == "ok":
                result["status"] = "success"
            if trace_id and "trace_id" not in result:
                result["trace_id"] = trace_id
            return compress_result(result)
        return fail(
            f"Handler for '{action}' returned {type(result).__name__}, expected dict",
            trace_id=trace_id,
        )
    except Exception as e:
        return fail(str(e), trace_id=trace_id)
