"""
tools/git.py — Git meta-tool for version control actions.

The LLM sees ONE tool: git(action, ...)
Supported actions: status, log, diff, commit, add, init, restore, rollback,
 snapshot, show, branch_list, branch_create, branch_delete, tag_list,
 tag_create, tag_delete, checkout_branch, checkout_new.

Default root: "agent" (the agent's own repository). Pass root="workspace" to
work on a project inside the workspace.

IMPORTANT - root vs path parameter:
 root - the repo directory: "agent" (default) | "workspace" | "/absolute/path"
 DEFAULT is "agent" – the agent's own source code.
 Use root="workspace" for project repos.
 path - ONLY used by diff to filter a specific file. NOT the repo directory.
 Exception: if you pass path="D:/mcp/agent" with root="workspace",
 the tool detects this and uses path as the root (backward-compat alias).

Commands intentionally excluded from autonomous execution:
 fetch, pull, merge, rebase, push
 These involve remote actions, destructive history rewrites, or conflict
 resolution, which require human judgement and are unsafe for unsupervised agents.
"""

from __future__ import annotations

from core.config import cfg
from registry import tool
from tools._meta_tool import meta_tool
from tools.git_ops._registry import DISPATCH
from tools.git_ops.helpers import _resolve_root, _check_repo
from core.path_guard import check_git_operation, make_path_error
from core.tracer import tracer
from core.utils import compress_result
from core.contracts import ok, fail


# ─────────────────────────────────────────────────────────────────────────────
# Dispatcher Implementation
# ─────────────────────────────────────────────────────────────────────────────
@tool
@meta_tool(
    DISPATCH.get("git", {}),
    doc_sections=[
        "IMPORTANT — root vs path parameter:",
        ' root — the repo directory: "agent" (default) | "workspace" | "/absolute/path"',
        ' DEFAULT is "agent" — the agent\'s own source code.',
        ' Use root="workspace" for project repos.',
        ' path — ONLY used by diff to filter a specific file. NOT the repo directory.',
        "",
        "Common usage patterns:",
        ' git(action="status")              # check working tree',
        ' git(action="log", n=5)            # recent commits',
        ' git(action="snapshot", message="...")  # safe point before changes',
        ' git(action="commit", message="...")    # after a successful change',
        ' git(action="rollback")            # undo uncommitted changes',
        "",
        "Commands intentionally excluded from autonomous execution:",
        " fetch, pull, merge, rebase, push",
        " These involve remote actions, destructive history rewrites, or",
        " conflict resolution, which require human judgement.",
    ],
)
def git(
    action: str = "",
    message: str = "",
    root: str = "agent",
    n: int = 10,
    path: str = "",
    force: bool = False,
    target: str = "",
    trace_id: str = "",
) -> dict:
    """
    Git version control actions. Dispatched via standardized registry.
    Docstring and action: Literal[...] are auto-generated by @meta_tool.
    """
    action = action.strip().lower()
    if not trace_id:
        trace_id = tracer.new_trace("git", goal=action)

    # Fast path: empty action parameter
    if not action:
        return fail(
            "action parameter is required. Valid actions are listed in the tool description.",
            trace_id=trace_id,
        )

    # Cancellation Guard: Abort before any git mutations
    from core.runtime.cancellation import ensure_not_cancelled
    ensure_not_cancelled(trace_id)

    # 1. Resolve working directory (preserves backward-compat alias logic)
    cwd, err = _resolve_root(root, path)
    if err:
        return make_path_error(path or root, action, err, trace_id)

    # 2. Validate git action scoping (blocks clone outside workspace)
    allowed, err, resolved_cwd = check_git_operation(
        operation=action,
        cwd=cwd,
        target=target if target else None
    )
    if not allowed:
        return make_path_error(cwd or path, action, err, trace_id)

    # Use resolved_cwd if provided
    actual_cwd = resolved_cwd or cwd

    # 3. Lookup action in registry
    git_ops = DISPATCH.get("git", {})
    op_info = git_ops.get(action)
    if not op_info:
        valid = " | ".join(sorted(git_ops.keys()))
        return fail(
            f"Unknown action '{action}'. Valid: {valid}",
            trace_id=trace_id,
        )

    # 4. Validate repository if the action requires it
    if op_info.get("needs_repo"):
        repo_ok, err = _check_repo(actual_cwd)
        if not repo_ok:
            return fail(err, trace_id=trace_id)

    # 5. Prepare kwargs exactly as original handlers expect
    kwargs = {
        "cwd": actual_cwd,
        "message": message,
        "path": path,
        "n": n,
        "force": force,
        "trace_id": trace_id,
    }

    if target:
        kwargs["target"] = target

    # 6. Execute handler safely
    try:
        result = op_info["func"](**kwargs)
        if isinstance(result, dict):
            if result.get("status") == "ok":
                result["status"] = "success"
            if trace_id and "trace_id" not in result:
                result["trace_id"] = trace_id
            return compress_result(result)
    except Exception as e:
        return fail(str(e), trace_id=trace_id)


# ---------------------------------------------------------------------------
# Commands intentionally excluded from the git meta-tool
# ---------------------------------------------------------------------------
# The following actions are NOT exposed to the autonomous agent because they
# either involve remote repositories, are destructive to shared history, or
# require human judgement for conflict resolution:
# fetch, pull, merge, rebase, push
