"""tools/report.py — Report meta-tool.

Thin @tool facade. Dispatches to report_core builders via auto-discovered actions.
All heavy imports are lazy — inside action handlers.

Architecture:
  @tool + @meta_tool(DISPATCH["report"])  →  auto-generated Literal + docstring
  Facade validates → merges preset → looks up handler → dispatches → wraps result
  Memory hook is fire-and-forget (except Exception: pass)
"""
from __future__ import annotations

from typing import Any

from core.tracer import tracer
from registry import tool

from tools._meta_tool import meta_tool
from tools.report_core._registry import DISPATCH, PRESETS
from tools.report_core.contracts import report_ok, report_fail

# ─────────────────────────────────────────────────────────────────────────────
# Dispatcher Implementation
# ─────────────────────────────────────────────────────────────────────────────
@tool
@meta_tool(
    DISPATCH.get("report", {}),
    doc_sections=[
        "IMPORTANT — data parameter:",
        ' data — inline dict/list, or a local file path string',
        ' data_path — alternative: specify path in config instead of data',
        "",
        "Common usage patterns:",
        ' report(action="chart", title="Revenue", data={"x":["Q1","Q2"], "y":[100,150]}, config={"chart_type":"bar"})',
        ' report(action="dashboard", title="Q3 Analysis", data="workspace/data.csv", preset="financial")',
        ' report(action="compare", title="Price Change", data={"before": {...}, "after": {...}})',
        ' report(action="timeline", title="Project Plan", data=[{"label":"Phase 1","start":"2026-01-01","end":"2026-02-15"}])',
        ' report(action="list")  # list all available actions',
        ' report(action="help", data="chart")  # get help for a specific action',
        "",
        "Presets available:",
        ' financial, code_audit, research, system_health, compare, timeline, scorecard',
    ],
)
def report(
    action: str = "",
    trace_id: str = "",
    title: str = "",
    data: Any = None,
    config: dict = None,
    preset: str = "",
) -> dict:
    """
    Report tool — create interactive charts, maps, reports, dashboards, and diagrams.
    Docstring and action: Literal[...] are auto-generated by @meta_tool.
    """
    action = (action or "").strip().lower()
    if not trace_id:
        trace_id = tracer.new_trace("report", goal=action)

    # Fast path: empty action parameter
    if not action:
        return report_fail(
            "action parameter is required. Valid actions are listed in the tool description.",
            trace_id=trace_id,
        )

    # Cancellation Guard: Abort before any report generation
    try:
        from core.runtime.cancellation import ensure_not_cancelled
        ensure_not_cancelled(trace_id)
    except BaseException:
        return report_fail("Workflow cancelled — aborting report operation", trace_id=trace_id)

    # 1. Apply preset
    config = dict(config) if config else {}
    if preset and preset in PRESETS:
        preset_cfg = dict(PRESETS[preset])
        preset_cfg.update(config)
        config = preset_cfg

    # 2. Lookup action in registry
    report_ops = DISPATCH.get("report", {})
    op_info = report_ops.get(action)
    if not op_info:
        valid = " | ".join(sorted(report_ops.keys()))
        return report_fail(
            f"Unknown action '{action}'. Valid: {valid}",
            trace_id=trace_id,
        )

    # 3. Dispatch
    try:
        result = op_info["func"](
            trace_id=trace_id,
            title=title,
            data=data,
            config=config,
        )
        # Memory hook — store episodic record of report generation
        try:
            from core.memory import memory
            memory.store_episodic(
                text=f"Generated {action} report: '{title}' at {result.get('html_path', 'unknown')}",
                importance=5,
                goal=title,
                outcome="success",
                tools_used=f"report,{action}",
                trace_id=trace_id,
            )
        except Exception:
            pass  # Never fail the report if memory storage fails
        return report_ok(result, trace_id=trace_id)
    except Exception as e:
        return report_fail(f"{type(e).__name__}: {e}", trace_id=trace_id)
