"""skills/ddm/focus/__init__.py -- Focus skill manifest + router.

DDM Focus (Boletim Focus) dashboard. 1 mode: dashboard (multi-tab).

  Tabs:
    1. Focus             (group: Boletim)    - 4 year subtabs (2026-2029)
    2. IPCA              (group: Indicadores) - 3 time-window subtabs + chart
    3. PIB Total         (group: Indicadores) - same
    4. Cambio            (group: Indicadores) - same
    5. Selic             (group: Indicadores) - same
    6. IGP-M             (group: Indicadores) - same
    7. IPCA Adm          (group: Indicadores) - same
    8. Conta corrente    (group: Indicadores) - same
    9. Balanca comercial (group: Indicadores) - same
    10. Investimento direto no pais (group: Indicadores) - same
    11. Divida liquida setor pub   (group: Indicadores) - same
    12. Resultado primario          (group: Indicadores) - same
    13. Resultado nominal           (group: Indicadores) - same

Calls data_sources.ddm.focus query_engine directly (read-only - no own DB).

[v1] Skill structure mirrors the ddm/acoes pattern (1 dashboard mode):
  - _registry.py        : MODES + register_mode via skills._base.make_registry()
                          (with a standalone fallback)
  - helpers.py          : format_value, format_int, comparison_symbol,
                          comparison_color, parse_numeric
  - report.py           : build_kpi_card, build_year_table, build_indicator_table,
                          build_indicator_chart, build_error_section
  - modes/<mode>.py     : @register_mode-decorated implementations
  - __init__.py         : auto_discover + MANIFEST + route (this file)

Auto-discovery (via _registry, which delegates to skills._base when merged
into the agent tree):
  1. _registry.py calls make_registry() to create focus's MODES dict.
  2. __init__.py calls auto_discover_modes(__name__) to import all modes/*.py.
  3. Each mode module's @register_mode decorator populates MODES.
  4. build_manifest_modes(MODES) turns the registry into MANIFEST["modes"].

Adding a new mode = drop a file in modes/ + register_mode(). No edits to
__init__.py or _registry.py needed.

[v1] Sync guard wired via required_sources=["ddm-focus"]. skills/_base
._trigger_sync sync_map has a "ddm-focus" entry that calls
sync_all(force=True) when ddm-focus is stale.
"""

from __future__ import annotations

from skills.ddm.focus._registry import (
    MODES, auto_discover_modes, make_route, build_manifest_modes,
)

# Auto-discover all mode modules from modes/ subdirectory.
auto_discover_modes(__name__)

# Data sources this skill needs. The route() wrapper checks freshness
# before each dispatch and triggers force-sync if stale. Tests use
# CVM_SKIP_SYNC=1 to bypass.
REQUIRED_SOURCES = ["ddm-focus"]

# Build MANIFEST from the registered modes.
MANIFEST = {
    "sub_domain":  "focus",
    "description": (
        "DDM Focus (Boletim Focus) dashboard - 13 tabs: 1 'Focus' tab "
        "with 4 year subtabs (2026-2029, each showing all 12 indicators) "
        "+ 12 per-indicator tabs (IPCA, PIB Total, Cambio, Selic, IGP-M, "
        "IPCA Adm, Conta corrente, Balanca comercial, Investimento direto "
        "no pais, Divida liquida setor pub, Resultado primario, Resultado "
        "nominal) each with a grouped bar chart + 3 time-window subtabs "
        "(Ha 4 semanas, 1 sem, Hoje). Data source: data_sources/ddm/focus/ "
        "(read-only queries against focus.db)."
    ),
    "source":  "data_sources/ddm/focus/ (read-only)",
    "storage": "read-only - no own database",
    "modes": build_manifest_modes(MODES),
    # Declared for manifest consumers + sync guard.
    "required_sources": REQUIRED_SOURCES,
}

# route() generated by make_route() with sync guard (when merged into the
# agent tree; standalone fallback has no sync guard - see _registry.py).
# Pass skip_sync=True per-call to bypass (e.g., for cached/quick lookups).
route = make_route("sub_domain", "focus", MODES,
                   required_sources=REQUIRED_SOURCES)
